blank_issues_enabled: false
contact_links:
  - name: "❓ Pergunta"
    url: https://github.com/orgs/Nucleo-de-Modernizacao-Governamental/discussions/new?category=q-a
    about: "Faça perguntas e participe de discussões."

# Forçando a atualização